### PR TITLE
Skip FirebaseFirestoreSwift on environment variable SKIP_FIREBASE_FIRESTORE_SWIFT

### PR DESCRIPTION
**Pull request by QuentinFarizon**

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This works for me and is generic even (a cordova-specific one would have been fine even, but generic is that much better). Nice!

**Comment by mikehardy** [comment]
Could you follow the instructions on the CLA comment above and get that signed? Then I'm  happy to merge this - it will take one release cycle (that is: when firebase-ios-sdk 10.3.0 releases, should be soon? They release about every 3 weeks) and then the next release generated will have this fix

**Comment by QuentinFarizon** [comment]
@mikehardy CLA signed

**Comment by QuentinFarizon** [comment]
(I've squashed)

**Comment by mikehardy** [comment]
Unfortunately it appears we *just* missed the 10.3.0 release cycle from firebase-ios-sdk - it went out just a few hours ago, but when 10.4.0 hits, this will be in place

**Comment by lucaele** [comment]
How and where i could set env SKIP_FIREBASE_FIRESTORE_SWIFT?
Thanks

**Pull request merged**
